version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8081:8080

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
